<?php

// for more info see:
// https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage
// https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/UPGRADE.md

if (class_exists('PhpCsFixer\Finder')) {    // PHP-CS-Fixer 2.x
    $finder = PhpCsFixer\Finder::create()
        ->in(__DIR__)
        ->exclude('var')
        ->exclude('config')
        ->exclude('var')
        ->exclude('public/bundles')
        ->exclude('public/build')
        // exclude files generated by Symfony Flex recipes
        ->notPath('bin/console')
        ->notPath('public/index.php')
    ;

    return PhpCsFixer\Config::create()
        ->setRules(array(
            '@PSR2' => true,
            '@Symfony'=>true,
            'blank_line_before_statement' => [
                'statements' => ['break','return'],
            ],
            'binary_operator_spaces' => [
                'default' => 'single_space',
                'operators' => [
                    '=>' => 'align'
                ]
            ],
            'array_syntax' => ['syntax' => 'short'],
            'ordered_imports' => true,
            'no_superfluous_phpdoc_tags' => true,
            'no_useless_else' => true,
            'no_useless_return' => true,
        ))
        ->setFinder($finder)
    ;
} elseif (class_exists('Symfony\CS\Finder\DefaultFinder')) {  // PHP-CS-Fixer 1.x
    $finder = Symfony\CS\Finder\DefaultFinder::create()
        ->in(__DIR__)
    ;

    return Symfony\CS\Config\Config::create()
        ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
        ->fixers(['-psr0'])    // don't lowercase namespace (use "namespace App\.." instead of "namespace app\..") to be compatible with Laravel 5
        ->finder($finder)
    ;
}