# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY
  param_fetcher_listener: true
  format_listener:
    rules:
      - {
          path: ^/,
          priorities: [json, xml, html],
          fallback_format: json,
          prefer_extension: true,
        }
  view:
    view_response_listener: force
    formats:
      xml: false
      json: true
    templating_formats:
      html: false
  exception:
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    messages:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
  allowed_methods_listener: true
  access_denied_listener:
    json: true
  body_listener: true
  serializer:
    serialize_null: true
  routing_loader:
    include_format: false
